[package]
name = "tinex"
version = "0.1.0"
edition = "2024"

[dependencies]
tinex-widgets = { path = "../tinex-widgets" }
tinex-core = { path = "../tinex-core" }
tinex-plugins = { path = "../tinex-plugins" }
anyhow = "1"
bumpalo = { version = "3.20.3", features = ["collections"] }
clap = { version = "4", features = ["derive"] }
jack = "0.13"
pollster = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
wmidi = "4.0.11"
vello = "0.10"
winit = "0.30"
